import { useMemo, useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, Bot, ChevronRight, CircleDollarSign, Globe2, Landmark, Menu, Newspaper, Shield, Sparkles, TrendingUp, Users, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { askAdvisor, generateProposalResult } from '@/lib/ai';
import { fallbackResult, issues, stateAbbr, states } from '@/lib/data';
import type { Citizen, Metrics, Party, Profile, ProposalResult, Screen, StateGrade } from '@/lib/types';

const initialMetrics: Metrics = { approval: 52, economy: 48, global: 61, crisis: 24, inflation: 2.1, deficit: -850, debt: 34000, gdp: 2.3, stability: 55, family: 70, foreign: 50 };
const parties: Party[] = ['Democratic', 'Republican', 'Independent', 'Unity Coalition'];

function App() {
  const [screen, setScreen] = useState<Screen>('home');
  const [profile, setProfile] = useState<Profile | null>(null);
  const [metrics, setMetrics] = useState<Metrics>(initialMetrics);
  const [month, setMonth] = useState(1);
  const [issueIndex, setIssueIndex] = useState(0);
  const [proposal, setProposal] = useState('');
  const [result, setResult] = useState<ProposalResult | null>(null);
  const [consults, setConsults] = useState(0);
  const [advisor, setAdvisor] = useState('');
  const [loading, setLoading] = useState(false);
  const [navOpen, setNavOpen] = useState(false);
  const [history, setHistory] = useState<string[]>([]);

  const createPresident = (newProfile: Profile) => { setProfile(newProfile); setScreen('home'); void supabase.from('game_sessions').insert({ player_name: newProfile.name, party: newProfile.party, vice_president: newProfile.vicePresident, election_margin: newProfile.margin }); };
  const advanceMonth = () => { const next = Math.min(48, month + 1); setMonth(next); setMetrics((current) => ({ ...current, inflation: Number((current.inflation + 0.02).toFixed(2)), debt: current.debt + 38, deficit: current.deficit - 8, stability: Math.max(0, current.stability - (next === 24 ? 3 : 0)) })); };
  const openProposal = () => { setProposal(''); setAdvisor(''); setConsults(0); setResult(null); setIssueIndex((current) => (current + 1) % issues.length); setScreen('proposal'); };
  const consultAdvisor = async () => { if (consults >= 2 || !proposal.trim()) return; setLoading(true); setAdvisor(await askAdvisor(proposal, issues[issueIndex].context)); setConsults((current) => current + 1); setLoading(false); };
  const enactProposal = async () => { if (!proposal.trim()) return; setLoading(true); const currentIssue = issues[issueIndex]; const generated = await generateProposalResult(
      currentIssue.title,
      proposal,
      currentIssue.context,
      issueIndex,
      JSON.stringify({
        month,
        president: profile?.name,
        party: profile?.party,
        approval: metrics.approval,
        economy: metrics.economy,
        inflation: metrics.inflation,
        deficit: metrics.deficit,
        debt: metrics.debt,
        gdp: metrics.gdp,
        stability: metrics.stability,
        foreignRelations: metrics.foreign,
        family: metrics.family,
      }),
    ); setResult(generated); setMetrics((current) => ({ ...current, ...Object.fromEntries(Object.entries(generated.metricChanges).map(([key, value]) => [key, (current[key as keyof Metrics] as number) + (value as number)])) })); setHistory((current) => [proposal, ...current]); setLoading(false); setScreen('summary'); void supabase.from('policies').insert({ month, title: proposal, category: generated.category, risk_economic: generated.economicRisk, risk_implementation: generated.implementationRisk, risk_public: generated.publicRisk, news_left: generated.news.left, news_right: generated.news.right, news_neutral: generated.news.neutral, state_reactions: generated.stateReactions, citizen_responses: generated.citizens, average_rating: Math.round(generated.citizens.reduce((sum, citizen) => sum + citizen.rating, 0) / generated.citizens.length), metric_changes: generated.metricChanges }); };

  if (!profile) return <CreatePresident onCreate={createPresident} />;
  const next = (target: Screen) => { setNavOpen(false); setScreen(target); };
  return <div className="app-shell"><header className="topbar"><div className="brand"><div className="seal"><Landmark size={17}/></div><div><b>THE NATION</b><small>A PRESIDENTIAL SIMULATION</small></div></div><nav className={navOpen ? 'mobile-open' : ''}><button onClick={() => next('home')}>The Briefing</button><button onClick={() => next('proposal')}>Policies</button><button onClick={() => next('election')}>Elections</button></nav><div className="president-chip"><span><small>THE 48TH PRESIDENT</small><b>{profile.name}</b></span><strong>{profile.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</strong></div><button className="menu-button" onClick={() => setNavOpen((open) => !open)}>{navOpen ? <X size={20}/> : <Menu size={20}/>}</button></header><main className="page-wrap">{screen === 'home' && <Home profile={profile} metrics={metrics} month={month} history={history} onProposal={openProposal} onAdvanceMonth={advanceMonth} onElection={() => next('election')}/>} {screen === 'proposal' && <Proposal issueIndex={issueIndex} proposal={proposal} setProposal={setProposal} advisor={advisor} consults={consults} loading={loading} onConsult={() => void consultAdvisor()} onEnact={() => void enactProposal()} onBack={() => next('home')}/>} {screen === 'summary' && result && <Summary result={result} onNext={() => next('news')}/>} {screen === 'news' && result && <News result={result} onNext={() => next('states')} onBack={() => next('summary')}/>} {screen === 'states' && result && <States result={result} onNext={() => next('citizens')} onBack={() => next('news')}/>} {screen === 'citizens' && result && <Citizens result={result} onNext={() => next('home')} onBack={() => next('states')}/>} {screen === 'election' && <Election month={month} metrics={metrics} onBack={() => next('home')}/>}</main></div>;
}

function CreatePresident({ onCreate }: { onCreate: (profile: Profile) => void }) { const [profile, setProfile] = useState<Profile>({ name: 'Alex Morgan', party: 'Independent', vicePresident: 'Sam Bennett', margin: 'Moderate victory' }); return <div className="landing"><div className="landing-noise"/><header className="landing-head"><div className="brand brand-light"><div className="seal seal-dark"><Landmark size={17}/></div><div><b>THE NATION</b><small>A PRESIDENTIAL SIMULATION</small></div></div><span>A living political drama</span></header><section className="landing-grid"><div><p className="eyebrow gold">THE OATH AWAITS</p><h1>Lead with<br/><i>consequence.</i></h1><p className="landing-copy">Make a country, not just a decision. Every proposal changes the economy, the states, your family, your coalition, and the world watching.</p><div className="landing-features"><span><Sparkles size={15}/> ADAPTIVE AI</span><span><Globe2 size={15}/> 48-MONTH TERM</span><span><Users size={15}/> LIVING PUBLIC</span></div></div><div className="creation-card"><p className="eyebrow">PRESIDENTIAL CREDENTIALS</p><label>Your name<input value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })}/></label><label>Political affiliation<select value={profile.party} onChange={(e) => setProfile({ ...profile, party: e.target.value as Party })}>{parties.map((party) => <option key={party}>{party}</option>)}</select></label><label>Vice President<input value={profile.vicePresident} onChange={(e) => setProfile({ ...profile, vicePresident: e.target.value })}/></label><label>Election victory<select value={profile.margin} onChange={(e) => setProfile({ ...profile, margin: e.target.value })}><option>Narrow victory</option><option>Moderate victory</option><option>Landslide victory</option></select></label><button className="button button-large" onClick={() => onCreate(profile)}>Enter the briefing room <ArrowRight size={16}/></button><small className="card-note">A fictional simulation of leadership, pressure, and public trust.</small></div></section><footer className="landing-foot"><span>SIMULATION 01</span><span>ALL DECISIONS ARE YOURS</span></footer></div>; }

function Home({ profile, metrics, month, history, onProposal, onAdvanceMonth, onElection }: { profile: Profile; metrics: Metrics; month: number; history: string[]; onProposal: () => void; onAdvanceMonth: () => void; onElection: () => void }) { const monthsToMidterm = Math.max(0, 24 - month); const monthsToElection = Math.max(0, 48 - month); return <section><div className="home-hero"><div><p className="eyebrow">THE OVAL OFFICE • {profile.party.toUpperCase()}</p><h1>Good morning,<br/><i>Mr. President.</i></h1><p className="hero-sub">The country is waiting for your next move. Your administration is on day {month * 30} of a four-year term.</p></div><div className="hero-date"><span>TERM ONE</span><b>MONTH {String(month).padStart(2, '0')}</b><small>of 48</small></div></div><div className="countdown-row"><div><small>MIDTERM ELECTION</small><b>{monthsToMidterm === 0 ? 'IN PROGRESS' : `${monthsToMidterm} MONTHS`}</b><span>House and Senate control at stake</span></div><div><small>REELECTION WINDOW</small><b>{monthsToElection} MONTHS</b><span>Your second-term mandate awaits</span></div><button onClick={monthsToMidterm === 0 ? onElection : onAdvanceMonth} className="button">{monthsToMidterm === 0 ? 'View midterms' : 'Advance one month'} <ArrowRight size={15}/></button></div><div className="section-head"><div><p className="eyebrow">NATIONAL PULSE</p><h2>The state of the nation</h2></div><span className="live-dot">● LIVE • {metrics.crisis > 45 ? 'TENSE' : 'STABLE'}</span></div><MetricsGrid metrics={metrics}/><div className="home-columns"><div><div className="section-head"><div><p className="eyebrow">YOUR AGENDA</p><h2>What will you propose?</h2></div></div><button className="proposal-cta" onClick={onProposal}><span><strong>Open the proposal desk</strong><small>Choose an issue or set your own agenda</small></span><span className="cta-arrow"><ArrowRight size={21}/></span></button></div><div className="history-box"><p className="eyebrow">SIGNED INTO LAW</p>{history.length === 0 ? <p className="muted">No policies yet. Your record begins today.</p> : history.slice(0, 4).map((policy, index) => <div className="history-line" key={`${policy}-${index}`}><span>0{index + 1}</span><p>{policy}</p></div>)}</div></div></section>; }

function MetricsGrid({ metrics }: { metrics: Metrics }) { const cards = [{ label: 'Approval rating', value: `${Math.round(metrics.approval)}%`, icon: TrendingUp, color: 'green' }, { label: 'Inflation', value: `${metrics.inflation.toFixed(1)}%`, icon: CircleDollarSign, color: 'orange' }, { label: 'GDP growth', value: `${metrics.gdp.toFixed(1)}%`, icon: BarChart3, color: 'green' }, { label: 'National debt', value: `$${Math.round(metrics.debt).toLocaleString()}B`, icon: Landmark, color: 'orange' }, { label: 'Government stability', value: `${Math.round(metrics.stability)}%`, icon: Shield, color: 'green' }, { label: 'Foreign relations', value: `${Math.round(metrics.foreign)}%`, icon: Globe2, color: 'blue' }]; return <div className="metrics-grid">{cards.map(({ label, value, icon: Icon, color }) => <div className="metric-card" key={label}><div className={`metric-icon ${color}`}><Icon size={17}/></div><small>{label}</small><strong>{value}</strong><div className="mini-bar"><i style={{ width: `${Math.min(100, typeof value === 'string' ? parseFloat(value) || 55 : 55)}%` }}/></div></div>)}</div>; }

function Proposal({ issueIndex, proposal, setProposal, advisor, consults, loading, onConsult, onEnact, onBack }: { issueIndex: number; proposal: string; setProposal: (value: string) => void; advisor: string; consults: number; loading: boolean; onConsult: () => void; onEnact: () => void; onBack: () => void }) { const issue = issues[issueIndex]; return <section className="flow-page"><button className="back-button" onClick={onBack}><ArrowLeft size={15}/> Back to the briefing</button><div className="flow-heading"><p className="eyebrow">PROPOSAL DESK • MONTH {issueIndex + 1}</p><h1>The decision in front of you</h1><p>Choose a response or write the policy you actually want. Your administration will live with the consequences.</p></div><div className="issue-layout"><div className="issue-card"><span className="tag">{issue.tag}</span><h2>{issue.title}</h2><p>{issue.context}</p><div className="choice-list">{issue.choices.map((choice) => <button key={choice} onClick={() => setProposal(choice)} className={proposal === choice ? 'selected-choice' : ''}><span>{choice}</span><ChevronRight size={17}/></button>)}</div><div className="or-line"><span>OR SET YOUR OWN AGENDA</span></div><textarea value={proposal} onChange={(e) => setProposal(e.target.value)} placeholder="Write the policy you want to propose..." rows={4}/><div className="proposal-actions"><button className="advisor-button" onClick={onConsult} disabled={loading || consults >= 2 || !proposal.trim()}><Bot size={17}/> Ask advisor <b>{2 - consults}/2</b></button><button className="button" onClick={onEnact} disabled={loading || !proposal.trim()}>{loading ? 'Preparing briefings...' : 'Advance with this proposal'} <ArrowRight size={16}/></button></div></div><aside className="advisor-panel"><div className="advisor-title"><Bot size={18}/><span><b>ADVISOR CHANNEL</b><small>PRIVATE • CHIEF OF STAFF</small></span></div>{advisor ? <p className="advisor-copy">“{advisor}”</p> : <p className="muted">Use your two private consultations carefully. Your chief of staff will flag the political and practical risks before you commit.</p>}<div className="consult-meter"><i style={{ width: `${consults * 50}%` }}/></div><small className="muted">{consults} of 2 consultations used this proposal</small></aside></div></section>; }

function Risk({ label, value, color }: { label: string; value: number; color: string }) { return <div className="risk"><div><span>{label}</span><b>{value}%</b></div><div className="risk-bar"><i className={color} style={{ width: `${value}%` }}/></div></div>; }
function Summary({ result, onNext }: { result: ProposalResult; onNext: () => void }) { return <FlowLayout eyebrow="POLICY BRIEF • PRIVATE REVIEW" title="The consequences begin now" subtitle="Before the headlines arrive, your senior team has modeled the first wave of impact." onNext={onNext} nextLabel="See the news reaction"><div className="summary-grid"><div className="summary-main"><span className="tag">POLICY SIGNED</span><span className="tag" style={{ marginLeft: 8 }}>AI MODELED • GEMINI</span><h2>{result.title}</h2><p className="summary-lead">Your proposal is moving from an announcement into the machinery of government. These are the risks your administration can see before implementation begins.</p><div className="risk-list"><Risk label="Economic risk" value={result.economicRisk} color="orange"/><Risk label="Implementation risk" value={result.implementationRisk} color="blue"/><Risk label="Public sensitivity" value={result.publicRisk} color="red"/></div></div><div className="impact-card"><p className="eyebrow">FIRST WAVE IMPACT</p>{Object.entries(result.metricChanges).slice(0, 5).map(([key, value]) => <div className="impact-line" key={key}><span>{key.replace(/([A-Z])/g, ' $1')}</span><b className={Number(value) >= 0 ? 'up' : 'down'}>{Number(value) >= 0 ? '+' : ''}{Number(value).toFixed(key === 'inflation' ? 1 : 0)}</b></div>)}</div></div></FlowLayout>; }
function News({ result, onNext, onBack }: { result: ProposalResult; onNext: () => void; onBack: () => void }) { return <FlowLayout eyebrow="THE MORNING EDITIONS" title="Three countries, one policy" subtitle="The same announcement lands differently depending on who is reading it." onNext={onNext} nextLabel="View state impact" onBack={onBack}><div className="news-grid"><NewsCard name="THE DAILY LEDGER" stance="LEFT LEANING" text={result.news.left} color="red"/><NewsCard name="THE NATIONAL REVIEW" stance="RIGHT LEANING" text={result.news.right} color="blue"/><NewsCard name="THE WIRE SERVICE" stance="NEUTRAL" text={result.news.neutral} color="gray"/></div></FlowLayout>; }
function NewsCard({ name, stance, text, color }: { name: string; stance: string; text: string; color: string }) { return <article className={`news-card ${color}`}><div><Newspaper size={18}/><span><b>{name}</b><small>{stance}</small></span></div><h3>{text}</h3><footer>POLICY DESK • 6:42 AM</footer></article>; }
function States({ result, onNext, onBack }: { result: ProposalResult; onNext: () => void; onBack: () => void }) { return <FlowLayout eyebrow="STATE OF THE UNION" title="The country, by state" subtitle="Local response is never uniform. Each state is graded by how the policy lands with its economy, voters, and elected leaders." onNext={onNext} nextLabel="Read the public" onBack={onBack}><div className="state-map">{states.map((state) => <div className={`state-tile ${result.stateReactions[state] || 'okay'}`} key={state}><b>{stateAbbr[state]}</b><small>{state}</small></div>)}</div><div className="legend"><span><i className="good"/> GOOD</span><span><i className="okay"/> MIXED</span><span><i className="bad"/> BAD</span></div></FlowLayout>; }
function Citizens({ result, onNext, onBack }: { result: ProposalResult; onNext: () => void; onBack: () => void }) { const average = Math.round(result.citizens.reduce((sum, citizen) => sum + citizen.rating, 0) / result.citizens.length); return <FlowLayout eyebrow="THE PUBLIC RESPONDS" title="What people are saying" subtitle="The first wave of reactions arrives from across the country. No one speaks for the whole public." onNext={onNext} nextLabel="Return to the briefing" onBack={onBack}><div className="citizen-head"><div><p className="eyebrow">SAMPLE OF 8,400 RESPONSES</p><h2>Citizen reaction</h2></div><div className="average"><small>AVERAGE RATING</small><b>{average}<em>/100</em></b></div></div><div className="citizen-list">{result.citizens.map((citizen) => <CitizenRow citizen={citizen} key={citizen.name}/>)}</div></FlowLayout>; }
function CitizenRow({ citizen }: { citizen: Citizen }) { return <article className="citizen-row"><div className="citizen-avatar">{citizen.name.split(' ').map((part) => part[0]).join('')}</div><div className="citizen-info"><div><b>{citizen.name}</b><small>{citizen.race} • {citizen.state}</small></div><p>{citizen.response}</p><span>{citizen.leaning}</span></div><strong className={citizen.rating > 65 ? 'rating-good' : citizen.rating < 45 ? 'rating-bad' : ''}>{citizen.rating}<small>/100</small></strong></article>; }
function FlowLayout({ eyebrow, title, subtitle, children, onNext, nextLabel, onBack }: { eyebrow: string; title: string; subtitle: string; children: ReactNode; onNext: () => void; nextLabel: string; onBack?: () => void }) { return <section className="flow-page">{onBack && <button className="back-button" onClick={onBack}><ArrowLeft size={15}/> Back</button>}<div className="flow-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div>{children}<div className="flow-footer"><span>BRIEFING CONTINUES</span><button className="button" onClick={onNext}>{nextLabel} <ArrowRight size={16}/></button></div></section>; }

function Election({ month, metrics, onBack }: { month: number; metrics: Metrics; onBack: () => void }) { const projected = useMemo(() => states.map((state, index) => ({ state, grade: (index + Math.round(metrics.approval)) % 4 === 0 ? 'bad' : (index + Math.round(metrics.global)) % 3 === 0 ? 'okay' : 'good' as StateGrade })), [metrics]); return <section className="flow-page"><button className="back-button" onClick={onBack}><ArrowLeft size={15}/> Back to the briefing</button><div className="flow-heading"><p className="eyebrow">ELECTION CENTER • MONTH {month}</p><h1>The map is moving.</h1><p>Every policy leaves a trail. This is your current polling picture, shown with a 3% margin of error.</p></div><div className="election-top"><div><small>PROJECTED ELECTORAL VOTE</small><b>{Math.round(270 + metrics.approval - 50)}</b><span>of 538</span></div><div><small>NATIONAL APPROVAL</small><b>{Math.round(metrics.approval)}%</b><span>±3% margin of error</span></div><div><small>TERM CLOCK</small><b>{48 - month}</b><span>months to election</span></div></div><div className="poll-map">{projected.map(({ state, grade }) => <div className={`poll-state ${grade}`} key={state}><b>{stateAbbr[state]}</b><span>{grade === 'good' ? 'D+' : grade === 'bad' ? 'R+' : 'TOSS'}</span></div>)}</div><div className="poll-legend"><span><i className="good"/> LEADING</span><span><i className="okay"/> WITHIN 3%</span><span><i className="bad"/> TRAILING</span></div></section>; }

export default App;
